### PR TITLE
Contributed

### PR DESCRIPTION
**Pull request by KIET7UKE**

### CODE REVIEW

**Comment by KIET7UKE** [comment]
@Knackie Bro can you please add hactoberfest2021 accepted label too

**Comment by Knackie** [comment]
Thanks !! Don't hesitate to give a star

**Comment by KIET7UKE** [comment]
Already Done bruh thanks!!!

**Comment by KIET7UKE** [comment]
Bro add hacktoberfest accepted label in my all 3prs please

**Pull request merged**
