### PR TITLE
Added Algo of Rod cutting problem in c lang

### PR DESCRIPTION
**Pull request by udita-22**

### CODE REVIEW

**Comment by Knackie** [comment]
Could you remove all useless file (DS_STORE, etc)

**Comment by udita-22** [comment]
> Could you remove all useless file (DS_STORE, etc)



Sure. I will do it

**Comment by Knackie** [comment]
Thanks ! don't hesitate to put a star

**Comment by udita-22** [comment]
> Thanks ! don't hesitate to put a star


yes sure

**Pull request merged**
